name: Run test

on:
  push:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Add your other steps here
